# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='grantedwish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishtitle', models.CharField(max_length=35)),
                ('wisher', models.CharField(max_length=35)),
                ('dateadded', models.DateField()),
                ('dategranted', models.DateField()),
                ('likes', models.CharField(max_length=25)),
                ('totalgranted', models.CharField(max_length=35)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='wishapp.account')),
                ('likers', models.ManyToManyField(related_name='liker', to='wishapp.account')),
            ],
        ),
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishtitle', models.CharField(max_length=35)),
                ('wishdesc', models.CharField(max_length=200)),
                ('dateadded', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish', to='wishapp.account')),
                ('grantedwish', models.ManyToManyField(related_name='wish', to='wishapp.grantedwish')),
            ],
        ),
    ]
